### ISSUE TITLE
Stylelint configuration

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/digital-buying-guide#5]
The [original configuration](https://github.com/open-contracting/digital-buying-guide/blob/856f53c686842633ba4e19db8cb2ae3fb08ebcee/.stylelintrc.yml) set 22 rules.

3 overlapped with https://github.com/stylelint-scss/stylelint-config-recommended-scss/blob/master/index.js

* at-rule-no-unknown (same)
* scss/at-rule-no-unknown (same)
* scss/at-extend-no-missing-placeholder (same)

5 overlapped with https://github.com/stylelint-scss/stylelint-config-standard-scss/blob/HEAD/index.js

* scss/dollar-variable-colon-space-after: always (versus always-single-line)
* scss/double-slash-comment-empty-line-before: always (but stylelint-config-standard-scss has conditions)
* scss/at-function-pattern: `^[a-z]+([a-z0-9-]+[a-z0-9]+)?$` (versus `^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$`)
* scss/dollar-variable-pattern (as above)
* scss/percent-placeholder-pattern (as above)

2 are deprecated https://stylelint.io/migration-guide/to-15/#deprecated-stylistic-rules

* number-leading-zero
* string-quotes

`scss/selector-no-redundant-nesting-selector: true # prevent unecessary use of nested &` seems to be gone (probably due to https://sass-lang.com/documentation/breaking-changes/mixed-decls/).

`value-no-vendor-prefix:  # disallow vendor prefixes, use auto-prefixer instead` is the same as not being specified.

The remaining are:

```yaml
declaration-no-important: true # disallow !important
at-rule-no-vendor-prefix: true # disallow vendor prefixes, use auto-prefixer instead
property-no-vendor-prefix: true # disallow vendor prefixes, use auto-prefixer instead
selector-no-vendor-prefix: true # disallow vendor prefixes, use auto-prefixer instead
function-url-quotes: always # url() contents must always be surrounded by quotes, in case they contain spaces
selector-attribute-quotes: always # enforce quotes in attribute selectors e.g. [target="_blank"]
font-family-name-quotes: always-where-required # ensure multi-word font names have quotes
selector-nested-pattern: "^(?!&(-|_))" # disallow nested styles to start with &- or &_ (BEM)
max-nesting-depth: 5 # restrict mega nesting inside selectors
selector-max-id: 0 # disallow IDs in selectors
```
